### ISSUE TITLE
Wrongly calculated value in first repeat group when used with once function

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/javarosa#636] opened 2021-06-28 06:58 UTC
#### Problem description
The problem has been discovered on the forum: https://forum.getodk.org/t/default-value-to-repeat-from-outside-repeat/33997/

#### Steps to reproduce the problem
1. Open the attached form:
[Default to Repeat.xlsx](https://github.com/getodk/javarosa/files/6724038/Default.to.Repeat.xlsx)
2. Answer `Current Job` question
3. Navigate to the next question which should display the answer passed in step 2 but it is just the first letter of that answer

#### Other information 
Removing once() in row 8 fixes the issue.

**Comment by lognaturel** [comment] 2021-06-28 13:20
We’re you able to reproduce without a field list? Did you try using dynamic defaults (set value) instead of once?

At first reading it doesn’t look like a JR problem. I believe it’s because it’s hitting the field-list recomputation triggered by Collect. I would expect the TextWatcher stuff to only apply to user-provided content so I’m not sure how but that’s the direction I would look in.

**Comment by lognaturel** [comment] 2021-06-28 21:09
This is working as expected because the value that is wrapped in `once` is in a field-list. That means it is committed to the form character-by-character.

**Closed by lognaturel** 2021-06-28 21:09 UTC
