### ISSUE TITLE
substr() returns results in lower-case

### ISSUE THREAD

**Issue by yanokwa** [getodk/javarosa#59] opened 2017-06-01 03:38 UTC
From kderra@gmail.com and https://groups.google.com/d/msg/opendatakit/bzUx6paP8MU/e4W7bOrTxncJ

> I make a pull data in the form with cascading selct. One of the key variable is a composite ID which is initialy in upper case. e.g id=RE067. When I want to keep the 2first two letters of the id variable, I got "re" and not "RE". I used this function : substr(${id},0,2)

**Comment by dcbriccetti** [comment] 2017-06-01 04:22
Interesting. It looks like it’s not the substr implementation. This test passes:

`testEval("substr('Hello',0, 2)", "He");`

**Comment by KDerra** [comment] 2017-06-02 14:40
[Cascading_indiv_Karim_June2017.xlsx](https://github.com/opendatakit/javarosa/files/1048000/Cascading_indiv_Karim_June2017.xlsx)

Hi Yaw,
I attached a very small test form.
Regards,
Karim

**Comment by KDerra** [comment] 2017-07-21 10:06
Dear dcbriccetti,
Pls can you more explain to me how it works ?
Regards,
Karim

**Comment by dcbriccetti** [comment] 2017-07-21 15:58
Hi @KDerra. That transformation isn’t happening from substr, so perhaps it is related to $(id).

**Comment by KDerra** [comment] 2017-07-21 16:14
Thanks dcbriccetti. another solution?

**Comment by grzesiek2010** [comment] 2023-09-26 11:42
I can confirm that `substring` functions work well. I've used this form for testing: 
[substringTest.xlsx](https://github.com/getodk/javarosa/files/12727027/substringTest.xlsx)
The form attached above used `cascading_select` question type that is not supported anymore. Maybe that was the cause. I think we can close this issue.

**Closed by grzesiek2010** 2023-09-26 11:42 UTC
Labels: bug, needs reproduction
